name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Updated to match the suggested version
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build iOS
        run: |
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign
          
      - name: Compress .app bundle
        run: |
          cd build/ios/iphoneos
          zip -r app-release.zip Runner.app
          
      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/app-release.zip